Adjust methods params for XIVLauncher.Core
ottercorp/FFXIVQuickLauncher pull request #54
Opened 2023-01-10 08:55 UTC by leonacco

modify some params of methods that the methods can be called by XIVlauncher.core. But the version is English after compile with XIVlauncher.Core.

2023-01-10 16:34 UTC, Bluefissure requested changes
删掉了的设置：
1. `dxvkFrameLimit`：限制 dxvk 帧数的设置，应该可以保留。
2. `moltenVK`：Mac 用户支持所需要的设置。

另外看到你修改了一些关于 patch verifier 的内容，你有经过测试吗？测试无误能不能把它单独提交成 PR？

2023-01-10 16:34 UTC, Bluefissure commented on src/XIVLauncher.Common.Unix/Compatibility/WineSettings.cs
> +        //this.MoltenVk = (modernMvkOn ?? false) ? "modern" : "stable";
`MoltenVk` 是给 Mac 用户提供的，上游同样没有，因为国际服有 XivOnMac 项目所以 XIVLauncher.Core 没有对 Mac 进行支持。国服团队无力维护多个登陆器（其实是没人写 Swift）所以在 XIVLauncher.Core 添加了 Mac 支持。

2023-01-10 16:34 UTC, Bluefissure commented on src/XIVLauncher.Common/Dalamud/DalamudLauncher.cs
> +    {       private readonly DalamudLoadMethod loadMethod;
indentation

2023-01-10 16:34 UTC, Bluefissure commented on src/XIVLauncher.Common/Game/Patch/PatchVerifier.cs
> +        public PatchVerifier(ISettings settings, Launcher.LoginResult loginResult, int progressUpdateInterval, int maxExpansion,bool external = true)
blank missing

2023-01-10 16:34 UTC, Bluefissure commented on src/XIVLauncher.Common/Game/Patch/PatchVerifier.cs
> +_external = external;
indentation

2023-01-11 03:37 UTC, leonacco commented on src/XIVLauncher.Common/Game/Patch/PatchVerifier.cs
> +        public async Task MoveUnnecessaryFiles(IndexedZiPatchIndexRemoteInstaller remote, string gamePath, HashSet<string> targetRelativePaths)
我记得没有动这个函数，可能用了老版本的xivlaunchercn

2023-01-11 03:39 UTC, leonacco commented on src/XIVLauncher.Common/Dalamud/DalamudLauncher.cs
> -                TroubleshootingPackData = this.troubleshootingData,
我记得没有动这个函数，可能用了老版本的xivlaunchercn

2023-01-11 03:39 UTC, leonacco commented on src/XIVLauncher.Common.Unix/Compatibility/CompatibilityTools.cs
> +    /* For matching the "https://github.com/goatcorp/XIVLauncher.Core" commit 386c6c8974170e594ddf2851701aef4a0dfb3a55
好的

2023-01-11 03:40 UTC, leonacco commented on src/XIVLauncher.Common.Unix/Compatibility/WineSettings.cs
> +        //this.MoltenVk = (modernMvkOn ?? false) ? "modern" : "stable";
嗯啊

2023-01-11 06:58 UTC, leonacco commented
All changes are based on original XIVlauncher.Core rather than XIVlauncher.Core(CN). So this PR should be closed

2023-01-11 06:58 UTC, closed without merging